name: matchingframe
version: 1.0.0+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  lottie: ^3.1.3
  http: 1.2.2
  flutter: 
    sdk: flutter
  ai_barcode_scanner: ^6.0.1
  barcode_scan2: ^4.3.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  image_path: "icons/matchingframelogo.jpg"
  android: true
  ios: true

flutter: 
  uses-material-design: true
  assets:
    - assets/animasi_car.json
    - assets/animasi_loading.json
    - assets/animasi_x.json
    - assets/animasi_ceklis.json
    - assets/animasi_delivery.json
